
spring:
  config:
    activate:
      on-profile: local

  # JPA 설정 (로컬: create로 초기화)
  jpa:
    hibernate:
      ddl-auto: create  # 매번 테이블 재생성 (테스트용)

  # 소셜 로그인 로직 테스트용(로컬)
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true  # static 매핑 활성화 (default true지만 명시)

  # 데이터베이스 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/BUB
    username: ${LOCAL_POSTGRESQL_USERNAME}
    password: ${LOCAL_POSTGRESQL_PASSWORD}


# jwt 설정
jwt:
  secret: ${LOCAL_JWT_SECRET} # 32바이트 이상의 매우 긴 무작위 문자열
  access-token-expiration-in-seconds: 3600 # 1시간 (보안을 위해 짧게 설정)
  refresh-token-expiration-in-seconds: 604800 # 7일 (사용자 편의를 위해 길게 설정)

# Swagger 설정 (local에서만 활성화 – Apidog 동기화용)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true