
spring:
  config:
    activate:
      on-profile: prod

  # jpa 설정
  jpa:
    hibernate:
      # (매우 중요) 운영 환경에서는 절대로 JPA가 스키마를 건드리지 않도록 'none'으로 설정합니다.
      ddl-auto: none

# HTTPS 설정 (HTTP를 HTTPS로 자동 리다이렉트)
server:
  http:
    redirect-to-https: true

  # postgreSQL 설정



  # 카카오 로그인 설정 (Production 앱 키, provider는 common에서 상속)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${PROD_KAKAO_REST_API_KEY}
            client-secret: ${PROD_KAKAO_CLIENT_SECRET}
            redirect-uri: https://yourdomain.com/auth/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post

# jwt 설정 (보안 강화)
jwt:
  secret: ${PROD_JWT_SECRET} # 32바이트 이상의 매우 긴 무작위 문자열
  access-token-expiration-in-seconds: 1800  # 더 짧게 (예: 30분)
  refresh-token-expiration-in-seconds: 2592000  # 30일

# 운영 환경에서는 일반적으로 불필요한 SQL 로그를 남기지 않도록 설정합니다.
# common.yml의 설정을 덮어쓰고 싶다면 아래와 같이 명시적으로 레벨을 지정할 수 있습니다.
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: info

# Swagger 설정(운영 환경에서는 비활성화)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false